---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: collectd
  name: collectd
spec:
  type: ClusterIP
  ports:
  - name: "25826"
    port: 25826
    protocol: UDP
  - name: "9187"
    port: 9187
  selector:
    app: collectd

---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collectd
  name: collectd-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collectd
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: collectd
    spec:
      containers:
      - image: collectd:0.6.1
        name: collectd
        command: [ "bash", "/home/collectd/start.sh" ]
        ports:
        - containerPort: 25826
          protocol: UDP
        - containerPort: 9187
          protocol: TCP
        volumeMounts:
        - mountPath: /home/collectd
          name: collectd-hostpath
          subPath: home
      restartPolicy: Always
      volumes:
      - name: collectd-hostpath
        hostPath:
          path: /home/wlc-server1/wlc_yaml/wlc_yaml/scripts/collectd/
          type: Directory

