---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: logstash
  name: syslog
spec:
  type: ClusterIP
  ports:
  - name: "512"
    port: 512
  - name: "9187"
    port: 9187
  selector:
    app: logstash

---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image:  logstash:0.6.1
        name: logstash
        command: [ "bash", "/home/logstash/start.sh" ]
        ports:
        - containerPort: 514
        - containerPort: 9187
        envFrom:
        - configMapRef:
            name: wlc
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /home/logstash
          name: syslog-hostpath
          subPath: home
      restartPolicy: Always
      volumes:
      - name: syslog-hostpath
        hostPath:
          path: /home/wlc-server1/wlc_yaml/wlc_yaml/scripts/logstash
          type: Directory

---

