---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: opennms
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-nfs-storage
  name: opennms-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: opennms
  name: opennms
spec:
  type: ClusterIP
  ports:
  - name: "8980"
    port: 8980
    targetPort: 8980
  - name: "8101"
    port: 8101
    targetPort: 8101
  - name: "61616"
    port: 61616
    targetPort: 61616
  - name: "10514"
    port: 10514
  - name: "1162"
    port: 1162
  - name: "9187"
    port: 9187
  selector:
    app: opennms

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opennms
  name: opennms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opennms
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opennms
    spec:
      containers:
      - command: ["/bin/bash", "/home/opennms.h/start.sh"]
        envFrom:
        - configMapRef:
            name: wlc
        image: opennms_24:0.7.1
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - -I
            - http://opennms:8980/opennms/login.jsp
          failureThreshold: 10
          periodSeconds: 60
          initialDelaySeconds: 180
          timeoutSeconds: 5
        name: opennms
        ports:
        - containerPort: 8101
        - containerPort: 8980
        - containerPort: 61616
        - containerPort: 10514
        - containerPort: 1162
        - containerPort: 9187
        resources: {}
        securityContext:
          capabilities:
           add: ["NET_ADMIN"]
          privileged: true
        volumeMounts:
 #       - mountPath: /opt/opennms/etc
 #         name: opennms-etc
        - mountPath: /opennms-data
          name: opennms-data
        - mountPath: /opt/opennms-etc-overlay
          name: opennms-hostpath
          subPath: etc-overlay
        - mountPath: /opt/opennms-jetty-webinf-overlay
          name: opennms-hostpath
          subPath: jetty-webinf-overlay
        - mountPath: /opt/opennms-overlay
          name: opennms-hostpath
          subPath: overlay
        - mountPath: /opt/opennms/assets
          name: opennms-hostpath
          subPath: assets
        - mountPath: /home/opennms.h
          name: opennms-hostpath
          subPath: home
        - mountPath: /home/ap_location_map
          name: opennms-hostpathnfs
          subPath: ap_location_map
        - mountPath: /home/import_location.properties
          name: opennms-hostpath
          subPath: import_location/import_location.properties
#        - mountPath: /home/branding
#          name: opennms-hostpath
#          subPath: branding
      restartPolicy: Always
      volumes:
      - name: opennms-data
        persistentVolumeClaim:
          claimName: opennms-pvc
      - name: opennms-hostpathnfs
        hostPath:
          path: /home/wlc-server1/wlc_yaml/wlc_yaml/scripts
          type: Directory
      - name: opennms-hostpath
        hostPath:
          path: /home/wlc-server1/wlc_yaml/wlc_yaml/scripts/opennms
          type: Directory

---

