apiVersion: v1
kind: ConfigMap
metadata:
   name: wlc
   labels:
     name: wlc-env
data:
  POSTGRES_HOST: stolon-proxy-service
  POSTGRES_PORT: "5432"
  POSTGRES_USER: stolon
  POSTGRES_PASSWORD: password1
  POSTGRES_DB: postgres
  OPENNMS_NB_TRAP_RECEIVER_HOST: trapreceiver
  OPENNMS_NB_TRAP_RECEIVER_PORT: "162"
  OPENNMS_NB_TRAP_RECEIVER_COMMUNITY: public
  OPENWISP_ADMIN_USER: admin
  OPENWISP_ADMIN_PASS: admin
  OPENNMS_DBPASS: opennms
  OPENNMS_DBNAME: opennms
  KAFKA_HOST: 192.168.1.14:6667,192.168.1.15:6667,192.168.1.16:6667
  WLCID: wlc001
  WLC_HEARTBEAT_INTERVAL: "300"
  WLC_UHN_NAME: uhn7kljc1hlfs001
  TZ: Asia/Tokyo
  LDAP_HOSTP1: ldap1:389
  LDAP_HOSTP2: ldap:389
  LDAP_BASE_DN: dc=rakuten,dc=com
  LDAP_BIND_USER: CN=admin,dc=rakuten,dc=com
  LDAP_BIND_PASS: "1234567890"
  LDAP_USER_FIRSTNAME_ATTR: givenname
  LDAP_USER_LASTNAME_ATTR: sn
  LDAP_USER_EMAIL_ATTR: mail
  LDAP_GROUPTYPE_ATTR: cn
  LDAP_RMP_ADMIN_GROUP: rmp_femto_wlc_admin
  LDAP_RMP_USER_GROUP: rmp_femto_wlc_user
  LDAP_RMP_TEST_GROUP: rmp_femto_wlc_test
  LDAP_GROUP_SEARCH_ATTR: member
  LDAP_GROUP_SEARCH_DN: ou=groups
  LDAP_USER_SEARCH_DN: ou=users
  LDAP_USERID_ATTR: uid
  GF_PATHS_CONFIG: /home/grafana/defaults.ini
  COLLECTD_KAFKA_TOPIC: collectd
  ELASTICSEARCH_HOST: 192.168.1.13:9200
  PHOENIXSERVERS: 192.168.1.15:2181
  REDISSERVER: 192.168.1.15
  REDISSERVER_SECONDARY: 192.168.1.16
  REDISSERVER_TERTIARY: 192.168.1.18
  REDISPORT: "6379"
  REDISPORT_PRIMARY: "26379"
  REDISPORT_SECONDARY: "26379"
  REDISPORT_TERTIARY: "26379"
  WLCAPP_HBASE_ZQ: datanode-2.novalocal,datanode-3.novalocal,datanode-1.novalocal
  POWER_FACTOR: "5"
  TIME_INTERVALS: "300000"
  RSSI_CF: "3.3"
  WLC_ID: WLC186-TT.MOBILE.RAKUTEN.CO.JP
  MAIL_HOST: localhost
  MAIL_PORT: "465"
  MAIL_SECURE: "true"
  MAIL_SERVICE: '"gmail"'
  MAIL_AUTH_USERNAME: ""
  MAIL_AUTH_PWD: ""
  OPENNMS_IP: opennms
  OPENWISP_IP: openwisp
  WLCAPP_IP: wlcapp
  GRAFANA_IP: gserver
  WLC_IP: wlc
  LOGSTASH_IP: syslog
  COLLECTD_IP: collectd
  DATABASE_IP: database
  WLCAM_IP: wlcam
  WLCPROM_IP: wlcprom
  RD_IP: rd

---

