---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: wlc
  name: wlc
spec:
  type: ClusterIP
  ports:
  - name: "80"
    port: 80
  - name: "8991"
    port: 8991
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "514"
    port: 514
  - name: "25826"
    port: 25826
    protocol: UDP
  - name: "11111"
    port: 11111
    protocol: UDP
  selector:
    app: wlc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wlc
  name: wlc-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wlc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wlc
    spec:
      containers:
      - command: ["/bin/bash", "/home/wlc/start_wlc.sh"]
        image: nginx:0.4.2
        name: wlcinit
        envFrom:
        - configMapRef:
            name: wlc
        ports:
        - containerPort: 80
        - containerPort: 8000
        - containerPort: 8991
        - containerPort: 514
        - containerPort: 25286
          protocol: UDP
        - containerPort: 11111
          protocol: UDP
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /home/wlc
          name: wlc-hostpath
          subPath: wlc-server/wlc/wlc/home
        - mountPath: /etc/nginx
          name: wlc-hostpath
          subPath: wlc-server/wlc/wlc/home/conf
      restartPolicy: Always
      volumes:
      - name: wlc-hostpath
        persistentVolumeClaim:
           claimName: shared-nfs-pvc
