---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: wlclb
  name: wlclb
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
  - name: "8000"
    port: 8000
  - name: "9000"
    port: 9000
  - name: "9113"
    port: 9113
  - name: "514"
    port: 514
  - name: "69"
    port: 69
  selector:
    app: wlclb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wlclb
  name: wlclb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wlclb
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wlclb
    spec:
      containers:
      - image:  haproxy:0.4.1
        name: haproxy
        command: [ "/bin/bash","/home/wlclb/start.sh", "-f", "/home/wlclb/haproxy.cfg" ]
        envFrom:
        - configMapRef:
            name: wlc
        securityContext:
          privileged: true
        ports:
        - containerPort: 8000
        - containerPort: 9000
        - containerPort: 9113
        - containerPort: 80
        - containerPort: 514
        - containerPort: 69
        volumeMounts:
        - mountPath: /home/wlclb
          name: wlclb-hostpath
          subPath: wlc-server/wlc/wlclb/home
        - mountPath: /home/empty
          name: wlclb-hostpath
          subPath: wlc-server/wlc/wlclb/empty
      restartPolicy: Always
      volumes:
      - name: wlclb-hostpath
        persistentVolumeClaim:
           claimName: shared-nfs-pvc
---

