---

apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: wlcapp
  name: wlcapp
spec:
  type: ClusterIP
  ports:
  - name: "8300"
    port: 8300
  - name: "8301"
    port: 8301
  - name: "8302"
    port: 8302
  - name: "8303"
    port: 8303
  - name: "8304"
    port: 8304
  - name: "8305"
    port: 8305
  - name: "8306"
    port: 8306
  - name: "8778"
    port: 8778
  selector:
    app: wlcapp


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wlcapp
  name: wlcapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wlcapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wlcapp
    spec:
      containers:
      - args:
        - /bin/bash
        - /home/wlcapp/start.sh
        envFrom:
        - configMapRef:
            name: wlc
        image: wlcapp:0.7.3
        name: wlcapp
        ports:
        - containerPort: 8300
        - containerPort: 8301
        - containerPort: 8302
        - containerPort: 8303
        - containerPort: 8304
        - containerPort: 8305
        - containerPort: 8306
        - containerPort: 8778
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /home/wlcapp
          name: wlcapp-hostpath
          subPath: wlc-server/wlc/wlcapp/home
        - mountPath: /opt/app-root/src/reports
          name: wlcapp-hostpath
          subPath: wlc-server/wlc/wlcapp/home/reports
        - mountPath: /home/ap_location_map
          name: wlc-hostpath
          subPath: wlc-server/wlc/ap_location_map
      restartPolicy: Always
      volumes:
      - name: wlcapp-hostpath
        persistentVolumeClaim:
           claimName: shared-nfs-pvc
      - name: wlc-hostpath
        persistentVolumeClaim:
           claimName: shared-nfs-pvc

---

